<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width,initial-scale=1.0" />
		<title>Async Await</title>
		<link rel="stylesheet" href="../base.css" />
	</head>

	<body>
		<script>
			function wait(ms = 0) {
				return new Promise((resolve) => {
					setTimeout(resolve, ms);
				});
			}

			function makePizza(toppings = []) {
				return new Promise(function(resolve, reject) {
					// reject if toppings includes pineapple
					if (toppings.includes("pineapple")) {
						reject("seriously?! this is a no pineapple household");
					}
					const amountOfTimeToBake = 500 + toppings.length * 200;
					// wait 1 second for the pizza to cook
					setTimeout(function() {
						// when you are ready, you can resolve this promise;
						resolve(
							`Here is your üçï with the toppings: ${toppings.join(", ")}`
						);
					}, amountOfTimeToBake);
					// if something goes wrong, we can reject this promise.
				});
			}

			function handleError(err) {
				console.log("Oh no! üçç");
				console.log(err);
			}
			async function go() {
				const pizza = await makePizza(["pineapple"]);
				console.log(pizza);
				return pizza;
			}

			// catch it at runtime with .catch()
			// go().catch(handleError);
			// can use .catch() on async functions

			// or make a safe function with a higher-order function
			function makeSafe(fn, errorHandler) {
				return function() {
					fn().catch(errorHandler);
				};
			}
			const safeGo = makeSafe(go, handleError);

			safeGo();
			// async function goGo() {
			// 	const result = await go();
			// }

			// goGo().catch(handleError);
		</script>
	</body>
</html>
